spring:
  application:
    name: demo


  datasource:
    url: jdbc:postgresql://localhost:5432/virtual_office
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: MyPassword@